services:
  mysql:
    hostname: mysql
    image: mysql:8.0.32
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"  # Mapeo el puerto 3307 en la máquina local al puerto 3306 dentro del contenedor
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./f1db.sql:/docker-entrypoint-initdb.d/f1db.sql
    networks:
      - data-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "f1user", "-pf1password"]
      interval: 5s
      timeout: 10s
      retries: 5

  trino:
    hostname: trino
    image: 'trinodb/trino:351'
    container_name: trino
    ports:
      - '8086:8080'
    volumes:
      - ./etc:/usr/lib/trino/etc:ro
    networks:
      - data-network

  mariadb:
    hostname: mariadb
    image: mariadb:10.5.8
    container_name: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: metastore_db
    networks:
      - data-network

  hive-metastore:
    hostname: hive-metastore
    image: 'bitsondatadev/hive-metastore:latest'
    container_name: hive-metastore
    ports:
      - '9083:9083' # Metastore Thrift
    volumes:
      - ./conf/metastore-site.xml:/opt/apache-hive-metastore-3.0.0-bin/conf/metastore-site.xml:ro
    environment:
      METASTORE_DB_HOSTNAME: mariadb
    depends_on:
      - mariadb
    networks:
      - data-network

  minio:
    hostname: minio
    image: minio/minio:RELEASE.2024-05-10T01-41-38Z
    container_name: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./data:/data
    environment:
      MINIO_ROOT_USER: minio_access_key
      MINIO_ROOT_PASSWORD: minio_secret_key
    command: server /data --console-address ":9001"
    networks:
      - data-network

  jupyter-pyspark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter-pyspark
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/lautaro/notebooks
      - ./data/shared:/home/lautaro/shared
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      JUPYTER_TOKEN: "dev"
    depends_on:
      - minio
      - trino
      - hive-metastore
      - mysql
    networks:
      - data-network

volumes:
  minio-data:
    driver: local

networks:
  data-network:
    driver: bridge